### ISSUE TITLE
Kernel module fails to load (Ubuntu 20.10, Kernel 5.8)

### ISSUE THREAD

**Issue by rafibaum** [ccp-project/ccp-kernel#23]
Recently I wanted to load the CCP kernel module to test the Copa congestion control algorithm, but came across this error when running `sudo ./ccp_kernel_load ipc=0` as described in the guide:

```
make -C /lib/modules/5.8.0-7642-generic/build M=/home/rafi/Development/Repos/ccp-kernel modules
make[1]: Entering directory '/usr/src/linux-headers-5.8.0-7642-generic'
make[1]: Leaving directory '/usr/src/linux-headers-5.8.0-7642-generic'
insmod: ERROR: could not insert module ./ccp.ko: File exists
[  254.926144] vboxdrv: 0000000000000000 VBoxDDR0.r0
[  254.955675] VMMR0InitVM: eflags=246 fKernelFeatures=0x0 (SUPKERNELFEATURES_SMAP=0)
[ 1032.826829] VMMR0InitVM: eflags=246 fKernelFeatures=0x0 (SUPKERNELFEATURES_SMAP=0)
[ 1422.358600] vboxdrv: 0000000000000000 VMMR0.r0
[ 1422.450674] vboxdrv: 0000000000000000 VBoxDDR0.r0
[ 1422.475581] VMMR0InitVM: eflags=246 fKernelFeatures=0x0 (SUPKERNELFEATURES_SMAP=0)
[ 1565.455151] vboxdrv: 0000000000000000 VMMR0.r0
[ 1565.562340] vboxdrv: 0000000000000000 VBoxDDR0.r0
[ 1565.585402] VMMR0InitVM: eflags=246 fKernelFeatures=0x0 (SUPKERNELFEATURES_SMAP=0)
[ 1648.440037] VMMR0InitVM: eflags=246 fKernelFeatures=0x0 (SUPKERNELFEATURES_SMAP=0)
reno cubic ccp
tee: /proc/sys/net/ipv4/tcp_allowed_congestion_control: No such file or directory
```

Came across this on PopOS 20.10, which is very similar to Ubuntu 20.10, using Kernel version 5.8.0-7642-generic. I tried this on Arch Linux as well and ran into the same issue. I'd appreciate any advice about how to solve this! Thanks in advance.

**Comment by akshayknarayan** [comment]
Thanks for the report! It looks like the kernel module is already loaded:
```
insmod: ERROR: could not insert module ./ccp.ko: File exists
```

and the output of `sudo cat /proc/sys/net/ipv4/tcp_allowed_congestion_control` is `reno cubic ccp`. You can do another check with `lsmod | grep ccp` or look through `/var/log/syslog` for messages that mention ccp.

I might try unloading the kernel module. If that fails, it is likely there is an active TCP connection that is using CCP for congestion control, and the kernel won't let you unload the kernel module until that connection is cleaned up.

After that, you should be able to reload the kernel module using your invocation.

I'm closing this for now, but feel free to reopen if you see any further issues.

**Comment by rafibaum** [comment]
Thanks for getting back to me. Took another look at it and I had some module loaded named `ccp` being used by `kvm_amd`. I unloaded `kvm_amd` which then allowed me to unload `ccp` and reload it. This is super strange since this is a day old installation and I hadn't loaded ccp before that invocation. Did CCP sneak into the Linux kernel at some point, or is it possible there's some other module with the same name being loaded? In addition, the content of `tcp_allowed_congestion_control` only showed `reno cubic` and the output with `ccp` from that script isn't actually the contents of that file, but some dynamically generated text which the script attempts to insert (and fails to). This was the only output I found in syslog which mentioned CCP:
```
Feb 12 11:25:51 pop-os kernel: [    6.619677] ccp 0000:0d:00.1: enabling device (0000 -> 0002)
Feb 12 11:25:51 pop-os kernel: [    6.619834] ccp 0000:0d:00.1: ccp: unable to access the device: you might be running a broken BIOS.
```
That occurs around the time I booted up my computer this morning. Not quite sure what's going on but either way it appears to load successfully now. Thanks for the help!

**Comment by akshayknarayan** [comment]
Looks like it is this: https://docs.oracle.com/cd/E93554_01/E92390/html/uek4_feature_crypto.html
Our congestion control ccp kernel module is not going to be upstreamed. The output you provided isn't from our kernel module - must be from the other one.

If you need to load both, I think renaming `ccp.ko` to, say, `ccp_cc.ko` or something might help.
