### ISSUE TITLE
ccp_connection not initialized, [ccp] [nl] message read failed: -81.

### ISSUE THREAD

**Issue by bhatramya** [ccp-project/ccp-kernel#28]
Hi,

I have been using CCP (ccp-kernel) to run my algorithms in python for quite some time now. Recently when I tried running an algorithm, I noticed that the output (overall throughput) appeared to be same, irrespective of the changes in the algorithm. The output remained similar when I tried running different algorithms. Later I noticed this message in /var/log/syslog. 

Mar 10 09:53:01 client1 kernel: [323799.383380] [ccp] freeing connection 143
Mar 10 09:53:01 client1 kernel: [323818.435914] [ccp] ccp_connection not initialized
Mar 10 09:53:01 client1 kernel: [323818.435916] [ccp] ccp_connection not initialized
Mar 10 09:53:01 client1 kernel: [323818.435918] [ccp] new flow
Mar 10 09:53:01 client1 kernel: [323818.436027] [ccp] starting connection 143
Mar 10 09:53:01 client1 kernel: [323818.436121] unable to install new program, table is full
Mar 10 09:53:01 client1 kernel: [323818.436124] could not install datapath program: -81
Mar 10 09:53:01 client1 kernel: [323818.436124] 
Mar 10 09:53:01 client1 kernel: [323818.436124] [ccp] [nl] message read failed: -81.

I haven't changed anything in ccp-kernel files. Can you please help me with this situation?
Regards,
Ramya

**Comment by akshayknarayan** [comment]
Hi, 
```
Mar 10 09:53:01 client1 kernel: [323818.436121] unable to install new program, table is full
Mar 10 09:53:01 client1 kernel: [323818.436124] could not install datapath program: -81
```
Those two messages indicate that the finite number of programs libccp has space for has been exhausted. There are two possible causes: 
1. You are trying to load more than `MAX_DATAPATH_PROGRAMS` number of datapath programs (defined here: https://github.com/ccp-project/ccp-kernel/blob/master/tcp_ccp.h#L11). Increasing this value would then solve the problem (but of course would require a larger allocation).
2. You are running into the known limitation explained here: https://github.com/ccp-project/libccp/blob/cb42dae5479ea39a61c449603710a84627f120ec/ccp.c#L444-L450

I don't know what CCA you are trying to implement, so if you are in cause (1), then you should just change the value locally and we can close this issue.  
If you are in cause (2), then while I cannot commit on a timeframe for fixing this issue myself, I would be happy to review and merge a PR that fixes it in libccp.

Hope this helps!

-Akshay

**Comment by bhatramya** [comment]
Hi,

Thank you for the suggestions! :)

The first workaround seems to solve the issue.

I will close this issue.

Regards,
Ramya

**Comment by akshayknarayan** [comment]
Nice!
